export const LABELS_DE = {
  // Personal
  name: "Name",
  dateOfBirth: "Geburtsdatum",
  placeOfBirth: "Geburtsort",
  nationality: "Staatsangehörigkeit",
  maritalStatus: "Familienstand",
  drivingLicense: "Führerschein",
  street: "Straße",
  plz: "PLZ",
  city: "Stadt",
  phone: "Telefon",
  email: "E-Mail",
  website: "Website",
  // Summary
  summary: "Profil",
  // Experience
  title: "Position",
  company: "Unternehmen",
  location: "Ort",
  currentRole: "Aktuelle Stelle",
  startDate: "Beginn (MM.JJJJ)",
  endDate: "Ende (MM.JJJJ)",
  bullets: "Aufzählungspunkte",
  addBullet: "Punkt hinzufügen",
  addExperience: "Berufserfahrung hinzufügen",
  // Education
  degree: "Abschluss",
  institution: "Institution",
  thesis: "Abschlussarbeit",
  grade: "Note",
  addEducation: "Ausbildung hinzufügen",
  // Skills
  categoryName: "Kategoriename",
  addSkillCategory: "Kategorie hinzufügen",
  // Languages
  language: "Sprache",
  level: "Niveau",
  addLanguage: "Sprache hinzufügen",
  // Projects
  projectName: "Name",
  url: "URL",
  addProject: "Projekt hinzufügen",
  // Volunteer
  role: "Funktion",
  organization: "Organisation",
  ongoing: "Laufend",
  description: "Beschreibung",
  addVolunteer: "Ehrenamt hinzufügen",
  // Extra
  certifications: "Zertifikate (eins pro Zeile)",
  interests: "Interessen",
  signatureLabel: "Unterschrift (Ort, Datum)",
  signatureInclude: "Einfügen",
  signatureCity: "Ort",
  signatureDate: "Datum",
  // Tabs
  tabPersonal: "Persönlich",
  tabSummary: "Profil",
  tabExperience: "Erfahrung",
  tabEducation: "Ausbildung",
  tabSkills: "Kenntnisse",
  tabLanguages: "Sprachen",
  tabProjects: "Projekte",
  tabMore: "Weitere",
  // Photo
  photo: "Foto",
  uploadPhoto: "Foto hochladen",
  replacePhoto: "Ersetzen",
  removePhoto: "Entfernen",
  // Empty states
  noExperience: "Noch keine Berufserfahrung",
  noExperienceDesc: "Füge deinen Werdegang hinzu — beginne mit der aktuellsten Stelle.",
  noEducation: "Noch keine Ausbildung",
  noEducationDesc: "Füge deine Abschlüsse, Berufsausbildungen oder Zertifikate hinzu.",
  noSkills: "Noch keine Kenntnisse",
  noSkillsDesc: "Gruppiere deine Fähigkeiten: IT-Kenntnisse, Methoden, Soft Skills.",
  noLanguages: "Noch keine Sprachen",
  noLanguagesDesc: "Füge Sprachen mit Niveau und optionalem CEFR-Level hinzu.",
  noProjects: "Noch keine Projekte",
  noProjectsDesc: "Füge Nebenprojekte, Open-Source-Beiträge oder Portfolio-Stücke hinzu.",
  noVolunteer: "Noch kein Ehrenamt",
  noVolunteerDesc: "Füge ehrenamtliche Tätigkeiten, Mentoring oder gemeinnütziges Engagement hinzu.",
  // Reset dialog
  resetTitle: "Alle Daten zurücksetzen?",
  resetDescription: "Dein gesamter Lebenslauf und alle Einstellungen werden gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
  resetCancel: "Abbrechen",
  resetConfirm: "Zurücksetzen",
  // CV file prefix
  cvPrefix: "Lebenslauf",
  // Version manager
  versionsTitle: "CV-Versionen",
  versionsDescription: "Speichere verschiedene Varianten deines Lebenslaufs.",
  versionPlaceholder: "Name der Version…",
  versionSave: "Speichern",
  noVersions: "Noch keine gespeicherten Versionen.",
  // Empty state banner
  newHere: "Neu hier?",
  newHereDescription: "Lade ein deutsches Beispiel, um zu sehen, wie der CV Maker funktioniert.",
  loadExample: "Beispiel laden",
  // Load example button
  exampleLabel: "Beispiel",
  loadExampleTitle: "Beispieldaten laden?",
  loadExampleDescription: "Dein aktueller Lebenslauf wird durch ein deutsches Beispiel (Max Mustermann) ersetzt. Dein hochgeladenes Foto bleibt erhalten.",
  loadExampleCancel: "Abbrechen",
  loadExampleConfirm: "Beispiel laden",
  loadExampleTooltip: "Beispiel-Lebenslauf laden",
  // Section config
  sidebarColumnLabel: "Seitenleiste",
  mainColumnLabel: "Hauptbereich",
  emptyColumnHint: "Leer",
  // Appearance
  sectionsHeading: "Abschnitte",
  contactOrderHeading: "Persönliche Daten",
  contactField_personalLine: "Persönliche Angaben",
  contactField_email: "E-Mail",
  contactField_phone: "Telefon",
  contactField_address: "Adresse",
  contactField_website: "Website",
  contactField_linkedin: "LinkedIn",
  contactField_xing: "XING",
  contrastWarnSevere: "Sehr geringer Kontrast — erfüllt WCAG AA für keinen Text",
  contrastWarnAA: "Zu geringer Kontrast für Fließtext (WCAG AA) — nur für große Überschriften geeignet",
  resizeHandleLabel: "Editor-Breite anpassen",
  photoRadius: "Ecken abrunden",
  photoPanX: "Horizontal verschieben",
  photoPanY: "Vertikal verschieben",
  photoZoom: "Zoom",
  monthSelectLabel: "Monat",
  yearSelectLabel: "Jahr",
  monthYearGroupLabel: "Monat und Jahr",
  versionLoad: "Version laden",
  versionRename: "Version umbenennen",
  versionDelete: "Version löschen",
  // Hidden text
  hiddenTextHeading: "Versteckter Text",
  hiddenTextLeft: "Links",
  hiddenTextRight: "Rechts",
  hiddenTextHint: "Wird nur in die PDF-Exporte eingefügt (Schriftgröße 1, weiß).",
  pdfMetadataHeading: "PDF-Metadaten",
  pdfSubjectLabel: "Betreff",
  pdfKeywordsLabel: "Schlagwörter (durch Komma getrennt)",
  pdfCreatorLabel: "Ersteller",
  // Analytics consent
  consentTitle: "Cookies & Analytics",
  consentBody: "Wir würden gerne anonyme Nutzungsstatistiken mit Google Analytics erheben, um den CV Maker zu verbessern. Dies ist optional.",
  consentAccept: "Akzeptieren",
  consentDecline: "Ablehnen",
  // Endorsement dialog
  endorsementTitle: "Du baust etwas Großartiges!",
  endorsementTagline: "Mit Herzblut entwickelt – von einer Person",
  endorsementDescription: "Dieses Tool ist kostenlos und Open Source – entstanden in Abendstunden und mit viel Kaffee. Wenn es dir geholfen hat, freut sich der Entwickler über eine kleine Geste.",
  endorsementStarHint: "Dauert 2 Sekunden, bedeutet alles",
  endorsementCoffeeHint: "Treibstoff für das nächste Feature",
  endorsementStarCta: "Auf GitHub sternen",
  endorsementCoffeeCta: "Spendier mir einen Kaffee",
  endorsementLaterCta: "Vielleicht später",
  endorsementThanks: "Danke, dass du hier bist",
  endorsementOpen: "Entwickler unterstützen",
  // Landing — navigation
  landing_nav_features: "Funktionen",
  landing_nav_templates: "Vorlagen",
  landing_nav_useCases: "Anwendungsfälle",
  landing_nav_faq: "FAQ",
  landing_nav_contact: "Kontakt",
  landing_openEditor: "Editor öffnen",
  landing_tryNow: "Jetzt ausprobieren",
  // Hero
  landing_heroBadge: "100 % kostenlos · Open Source",
  landing_heroTitle: "Dein Lebenslauf.\nIn Minuten, nicht Stunden.",
  landing_heroSubtitle: "Ein datenschutzfreundlicher CV-Builder für den deutschen Arbeitsmarkt. DIN 5008, Live-Vorschau, 10 Vorlagen — alles kostenfrei, direkt im Browser.",
  landing_heroCta: "Editor öffnen",
  landing_heroCtaSecondary: "Beispiel-Lebenslauf ansehen",
  landing_heroSubCta: "Keine Anmeldung · Kein Tracking · Daten bleiben auf deinem Gerät",
  landing_heroMockName: "Max Mustermann",
  landing_heroMockRole: "Senior Frontend Engineer",
  landing_heroMockLine: "München · max@example.de · +49 151 23456789",
  // Features
  landing_featuresEyebrow: "Funktionen",
  landing_featuresTitle: "Alles was du brauchst — nichts was du nicht brauchst",
  landing_featuresSubtitle: "Sorgfältig kuratierte Funktionen für einen Lebenslauf, der deutschen Standards entspricht und auch international überzeugt.",
  landing_feature_preview_title: "Live-Vorschau",
  landing_feature_preview_body: "Jede Änderung erscheint sofort auf einer maßstabsgetreuen A4-Seite. Kein Raten, kein Rendern.",
  landing_feature_templates_title: "10 ATS-geeignete Vorlagen",
  landing_feature_templates_body: "Von klassisch-tabellarisch bis modern-minimalistisch. Inhalt bleibt, Layout wechselt mit einem Klick.",
  landing_feature_din_title: "DIN 5008 konform",
  landing_feature_din_body: "Datumsformate, Anschrift, Schriftgrößen — angepasst an den deutschen Standard, den HR erwartet.",
  landing_feature_export_title: "Überall exportieren",
  landing_feature_export_body: "PDF, DOCX, ATS-optimiertes PDF und JSON. Alle Exporte laufen lokal — deine Daten verlassen das Gerät nicht.",
  landing_feature_bilingual_title: "Zweisprachig (DE/EN)",
  landing_feature_bilingual_body: "Abschnittstitel, Datumsformate und UI auf Knopfdruck umschalten. Ideal für internationale Bewerbungen.",
  landing_feature_privacy_title: "Privacy-first",
  landing_feature_privacy_body: "Deine Daten liegen ausschließlich in deinem Browser. Keine Server, keine Accounts, keine Werbetracker.",
  landing_feature_versions_title: "Versionen speichern",
  landing_feature_versions_body: "Bis zu 20 Varianten parallel pflegen — eine pro Stelle, pro Branche oder pro Sprache.",
  landing_feature_undo_title: "Unbegrenztes Undo",
  landing_feature_undo_body: "20 Schritte Historie, Tastenkürzel inklusive. Experimentieren ohne Angst.",
  // Use cases
  landing_useCasesEyebrow: "Anwendungsfälle",
  landing_useCasesTitle: "Gebaut für echte Bewerber",
  landing_useCasesSubtitle: "Ob Berufseinstieg, Wechsel oder internationale Bewerbung — die passenden Vorlagen sind dabei.",
  landing_useCase_german_title: "Deutscher Arbeitsmarkt",
  landing_useCase_german_body: "Klassischer Lebenslauf mit Foto, Geburtsdatum, Nationalität und tabellarischer Struktur — genau so wie HR es in Deutschland erwartet.",
  landing_useCase_international_title: "Internationale Bewerbung",
  landing_useCase_international_body: "Englische Abschnittstitel, US-Datumsformat, optional ohne Foto. Ein Klick, zwei Sprachen.",
  landing_useCase_changer_title: "Quereinsteiger",
  landing_useCase_changer_body: "Betone Fähigkeiten statt Chronologie: konfigurierbare Abschnitte, hervorgehobene Projekte, flexibles Ordering.",
  landing_useCase_variants_title: "Mehrere Varianten",
  landing_useCase_variants_body: "Speichere eine maßgeschneiderte Version pro Stelle, ohne dein Haupt-CV zu überschreiben.",
  // Templates
  landing_templatesEyebrow: "Vorlagen",
  landing_templatesTitle: "10 professionelle Vorlagen",
  landing_templatesSubtitle: "Such dir eine aus — dein Inhalt bleibt. Jederzeit wechselbar.",
  landing_templates_ats: "ATS-sicher",
  landing_templates_twoCol: "Zwei Spalten",
  // Free section
  landing_freeEyebrow: "Preis",
  landing_freeTitle: "Wirklich kostenlos.",
  landing_freeBody: "Keine versteckten Kosten, keine Testphase, keine Paywall beim Export. Wenn du Zeit sparst, freut sich ein Stern auf GitHub oder ein Kaffee.",
  landing_freeBullet1: "Keine Werbung",
  landing_freeBullet2: "Keine Paywall beim Export",
  landing_freeBullet3: "Kein Account nötig",
  landing_freeBullet4: "Open Source auf GitHub",
  // JSON section
  landing_jsonEyebrow: "Dateneigentum",
  landing_jsonTitle: "Deine Daten gehören dir",
  landing_jsonSubtitle: "Importiere und exportiere deinen Lebenslauf als portables JSON. Versioniere ihn mit Git, diffe ihn, nimm ihn mit.",
  landing_jsonCopy: "Kopieren",
  landing_jsonCopied: "Kopiert",
  landing_jsonWhyTitle: "Warum JSON?",
  landing_jsonWhy1: "Portabel — funktioniert mit jedem Editor",
  landing_jsonWhy2: "Versionierbar — Git-freundlich",
  landing_jsonWhy3: "Zukunftssicher — offener Standard",
  landing_jsonWhy4: "Automatisierbar — in KI-Pipelines einsetzbar",
  // FAQ
  landing_faqEyebrow: "FAQ",
  landing_faqTitle: "Häufige Fragen",
  landing_faq_free_q: "Ist es wirklich kostenlos?",
  landing_faq_free_a: "Ja. Alle Funktionen — Vorlagen, PDF/DOCX-Export, Versionen, mehrere Sprachen — sind kostenlos und werden es bleiben. Das Projekt ist Open Source und freut sich über einen Stern auf GitHub.",
  landing_faq_data_q: "Wo werden meine Daten gespeichert?",
  landing_faq_data_a: "Ausschließlich lokal in deinem Browser (LocalStorage). Es gibt keinen Server, keine Cloud, keinen Account. Wenn du den Browser leerst, sind die Daten weg — exportiere also regelmäßig als JSON oder PDF.",
  landing_faq_german_q: "Entspricht der CV deutschen Lebenslauf-Standards?",
  landing_faq_german_a: "Ja. Die Vorlagen berücksichtigen DIN 5008, korrekte Datumsformate (MM.JJJJ), deutsche Abschnittstitel, Geburtsdatum und Nationalität. Einige Vorlagen (z. B. „Tabellarisch\") sind explizit am klassischen deutschen CV orientiert.",
  landing_faq_ats_q: "Ist der Export ATS-kompatibel?",
  landing_faq_ats_a: "Acht von zehn Vorlagen sind ATS-geeignet (einspaltig, klare Struktur). Zusätzlich gibt es einen separaten „ATS-PDF\"-Export, der eine reine Text-Variante ohne Design-Elemente erzeugt — ideal für automatische Bewerbungssysteme.",
  landing_faq_offline_q: "Funktioniert es offline?",
  landing_faq_offline_a: "Nach dem ersten Laden: ja. Bearbeitung, Vorschau und Export laufen vollständig im Browser. Keine Internetverbindung nötig.",
  landing_faq_formats_q: "Welche Exportformate gibt es?",
  landing_faq_formats_a: "PDF (gestyltes A4), ATS-PDF (reiner Text für Bewerbungssysteme), DOCX (Word-bearbeitbar) und JSON (für Backup und Versionierung).",
  landing_faq_devices_q: "Kann ich es auf dem Handy nutzen?",
  landing_faq_devices_a: "Ja. Der Editor passt sich an Mobilgeräte an mit Edit/Preview-Tabs. Für längere Bearbeitungen empfehlen wir Tablet oder Desktop.",
  landing_faq_multiple_q: "Kann ich mehrere Versionen speichern?",
  landing_faq_multiple_a: "Ja, bis zu 20 Snapshots. Jeder Snapshot enthält Inhalt und Layout. Du kannst sie benennen, laden und umbenennen — ideal für unterschiedliche Stellenausschreibungen.",
  // Contact
  landing_contactEyebrow: "Kontakt",
  landing_contactTitle: "Feedback, Bugs, Ideen",
  landing_contactBody: "Dieses Projekt lebt von Feedback. Mach einen Bug auf, schlage eine Funktion vor oder gib uns einen Stern, wenn es dir geholfen hat.",
  landing_contact_github: "GitHub-Issue öffnen",
  landing_contact_star: "Auf GitHub sternen",
  landing_contact_email: "Nachricht schreiben",
  landing_contact_coffee: "Spendier mir einen Kaffee",
  // Contact dialog
  landing_contactDialog_title: "Nachricht an den Entwickler",
  landing_contactDialog_description: "Hinterlasse kurz deine E-Mail und deine Nachricht — beim Absenden öffnet sich dein Mail-Programm mit allem vorausgefüllt.",
  landing_contactDialog_emailLabel: "Deine E-Mail",
  landing_contactDialog_emailPlaceholder: "du@example.com",
  landing_contactDialog_messageLabel: "Nachricht",
  landing_contactDialog_messagePlaceholder: "Was möchtest du teilen? Feedback, Bug, Idee…",
  landing_contactDialog_submit: "Mail-Programm öffnen",
  landing_contactDialog_submitDirect: "Nachricht senden",
  landing_contactDialog_cancel: "Abbrechen",
  landing_contactDialog_hint: "Dein Mail-Programm öffnet sich mit vorausgefüllter Nachricht — nichts wird ohne deine Bestätigung gesendet.",
  landing_contactDialog_hintDirect: "Deine Nachricht wird direkt an den Entwickler geschickt. Deine E-Mail wird nur für die Antwort verwendet.",
  landing_contactDialog_errorEmail: "Bitte gib eine gültige E-Mail-Adresse an.",
  landing_contactDialog_errorMessage: "Bitte schreibe mindestens ein paar Wörter.",
  landing_contactDialog_submitting: "Wird gesendet…",
  landing_contactDialog_successTitle: "Nachricht gesendet",
  landing_contactDialog_successBody: "Danke! Ich melde mich so bald wie möglich.",
  landing_contactDialog_successClose: "Schließen",
  landing_contactDialog_errorSubmit: "Senden fehlgeschlagen. Bitte versuch es gleich nochmal oder schick eine E-Mail.",
  // Final CTA
  landing_finalCtaTitle: "Bereit loszulegen?",
  landing_finalCtaBody: "Dein nächster Lebenslauf ist nur wenige Klicks entfernt.",
  landing_finalCtaButton: "Editor öffnen — kostenlos",
  // Footer
  landing_footerTagline: "Datenschutzfreundlicher CV-Builder für den deutschen Arbeitsmarkt",
  landing_footerMadeWith: "Gebaut mit React, TypeScript & Tailwind",
  landing_footerRights: "Open Source · Nicht-kommerzielle Lizenz",
} as const
