import type { LABELS_DE } from "./editor-labels.de"

// Enforce 1:1 key coverage with the DE locale at compile time.
export const LABELS_EN: Record<keyof typeof LABELS_DE, string> = {
  // Personal
  name: "Name",
  dateOfBirth: "Date of birth",
  placeOfBirth: "Place of birth",
  nationality: "Nationality",
  maritalStatus: "Marital status",
  drivingLicense: "Driving license",
  street: "Street",
  plz: "Postal code",
  city: "City",
  phone: "Phone",
  email: "Email",
  website: "Website",
  // Summary
  summary: "Summary",
  // Experience
  title: "Title",
  company: "Company",
  location: "Location",
  currentRole: "Current role",
  startDate: "Start (MM.YYYY)",
  endDate: "End (MM.YYYY)",
  bullets: "Bullets",
  addBullet: "Add bullet",
  addExperience: "Add experience",
  // Education
  degree: "Degree",
  institution: "Institution",
  thesis: "Thesis",
  grade: "Grade (Note)",
  addEducation: "Add education",
  // Skills
  categoryName: "Category name",
  addSkillCategory: "Add skill category",
  // Languages
  language: "Language",
  level: "Level",
  addLanguage: "Add language",
  // Projects
  projectName: "Name",
  url: "URL",
  addProject: "Add project",
  // Volunteer
  role: "Role",
  organization: "Organization",
  ongoing: "Ongoing",
  description: "Description",
  addVolunteer: "Add volunteer work",
  // Extra
  certifications: "Certifications (one per line)",
  interests: "Interests",
  signatureLabel: "Signature (Place, Date)",
  signatureInclude: "Include",
  signatureCity: "City (Ort)",
  signatureDate: "Date (Datum)",
  // Tabs
  tabPersonal: "Personal",
  tabSummary: "Summary",
  tabExperience: "Experience",
  tabEducation: "Education",
  tabSkills: "Skills",
  tabLanguages: "Languages",
  tabProjects: "Projects",
  tabMore: "More",
  // Photo
  photo: "Photo",
  uploadPhoto: "Upload photo",
  replacePhoto: "Replace",
  removePhoto: "Remove",
  // Empty states
  noExperience: "No experience yet",
  noExperienceDesc: "Add your work history — start with your most recent role.",
  noEducation: "No education yet",
  noEducationDesc: "Add your degrees, vocational training, or certifications.",
  noSkills: "No skills yet",
  noSkillsDesc: "Group your skills by category: Technical, Methods, Soft Skills.",
  noLanguages: "No languages yet",
  noLanguagesDesc: "Add languages with proficiency level and optional CEFR rating.",
  noProjects: "No projects yet",
  noProjectsDesc: "Add side projects, open-source work, or portfolio pieces.",
  noVolunteer: "No volunteer work yet",
  noVolunteerDesc: "Add community service, mentoring, or nonprofit involvement.",
  // Reset dialog
  resetTitle: "Reset all data?",
  resetDescription: "Your entire CV and all settings will be deleted. This action cannot be undone.",
  resetCancel: "Cancel",
  resetConfirm: "Reset",
  // CV file prefix
  cvPrefix: "cv",
  // Version manager
  versionsTitle: "CV Versions",
  versionsDescription: "Save different variants of your CV.",
  versionPlaceholder: "Version name…",
  versionSave: "Save",
  noVersions: "No saved versions yet.",
  // Empty state banner
  newHere: "New here?",
  newHereDescription: "Load a German example to see how the CV Maker works.",
  loadExample: "Load example",
  // Load example button
  exampleLabel: "Example",
  loadExampleTitle: "Load example data?",
  loadExampleDescription: "Your current CV will be replaced with a German example (Max Mustermann). Your uploaded photo will be kept.",
  loadExampleCancel: "Cancel",
  loadExampleConfirm: "Load example",
  loadExampleTooltip: "Load example CV",
  // Section config
  sidebarColumnLabel: "Sidebar",
  mainColumnLabel: "Main",
  emptyColumnHint: "Empty",
  // Appearance
  sectionsHeading: "Sections",
  contactOrderHeading: "Personal Info",
  contactField_personalLine: "Personal details",
  contactField_email: "Email",
  contactField_phone: "Phone",
  contactField_address: "Address",
  contactField_website: "Website",
  contactField_linkedin: "LinkedIn",
  contactField_xing: "XING",
  contrastWarnSevere: "Very low contrast — fails WCAG AA for any text",
  contrastWarnAA: "Too low for body text (WCAG AA) — OK for large headings only",
  resizeHandleLabel: "Resize editor panel",
  photoRadius: "Corner radius",
  photoPanX: "Pan horizontally",
  photoPanY: "Pan vertically",
  photoZoom: "Zoom",
  monthSelectLabel: "Month",
  yearSelectLabel: "Year",
  monthYearGroupLabel: "Month and year",
  versionLoad: "Load version",
  versionRename: "Rename version",
  versionDelete: "Delete version",
  // Hidden text
  hiddenTextHeading: "Hidden Text",
  hiddenTextLeft: "Left",
  hiddenTextRight: "Right",
  hiddenTextHint: "Injected into PDF exports only (font size 1, white).",
  pdfMetadataHeading: "PDF Metadata",
  pdfSubjectLabel: "Subject",
  pdfKeywordsLabel: "Keywords (comma-separated)",
  pdfCreatorLabel: "Creator",
  // Analytics consent
  consentTitle: "Cookies & analytics",
  consentBody: "We'd like to collect anonymous usage statistics via Google Analytics to improve CV Maker. This is optional.",
  consentAccept: "Accept",
  consentDecline: "Decline",
  // Endorsement dialog
  endorsementTitle: "You're building something great!",
  endorsementTagline: "Made with care by a solo developer",
  endorsementDescription: "This tool is free and open-source — built in spare evenings and powered by coffee. If it helped you land interviews, a small gesture goes a long way.",
  endorsementStarHint: "Takes 2 seconds, means the world",
  endorsementCoffeeHint: "Fuel the next feature",
  endorsementStarCta: "Star on GitHub",
  endorsementCoffeeCta: "Buy me a coffee",
  endorsementLaterCta: "Maybe later",
  endorsementThanks: "Thanks for being here",
  endorsementOpen: "Support the developer",
  // Landing — navigation
  landing_nav_features: "Features",
  landing_nav_templates: "Templates",
  landing_nav_useCases: "Use cases",
  landing_nav_faq: "FAQ",
  landing_nav_contact: "Contact",
  landing_openEditor: "Open editor",
  landing_tryNow: "Try it now",
  // Hero
  landing_heroBadge: "100% free · Open source",
  landing_heroTitle: "Your Lebenslauf.\nBuilt in minutes, not hours.",
  landing_heroSubtitle: "A privacy-first CV builder for the German job market. DIN 5008, live preview, 10 templates — all free, all in your browser.",
  landing_heroCta: "Open the editor",
  landing_heroCtaSecondary: "See example CV",
  landing_heroSubCta: "No sign-up · No tracking · Data stays on your device",
  landing_heroMockName: "Max Mustermann",
  landing_heroMockRole: "Senior Frontend Engineer",
  landing_heroMockLine: "Munich · max@example.de · +49 151 23456789",
  // Features
  landing_featuresEyebrow: "Features",
  landing_featuresTitle: "Everything you need — nothing you don't",
  landing_featuresSubtitle: "Carefully curated features for a CV that meets German standards and still works internationally.",
  landing_feature_preview_title: "Live preview",
  landing_feature_preview_body: "Every change appears instantly on a scaled A4 page. No guessing, no re-rendering.",
  landing_feature_templates_title: "10 ATS-ready templates",
  landing_feature_templates_body: "From classic tabular to modern minimalist. Your content stays — swap the layout in one click.",
  landing_feature_din_title: "DIN 5008 compliant",
  landing_feature_din_body: "Date formats, address layout, font sizes — matched to the German standard that HR expects.",
  landing_feature_export_title: "Export anywhere",
  landing_feature_export_body: "PDF, DOCX, ATS-optimized PDF, and JSON. All exports run locally — your data never leaves the device.",
  landing_feature_bilingual_title: "Bilingual (DE/EN)",
  landing_feature_bilingual_body: "Section titles, date formats, and UI toggle on demand. Ideal for international applications.",
  landing_feature_privacy_title: "Privacy-first",
  landing_feature_privacy_body: "Your data lives only in your browser. No servers, no accounts, no ad trackers.",
  landing_feature_versions_title: "Save versions",
  landing_feature_versions_body: "Keep up to 20 variants side-by-side — one per role, industry, or language.",
  landing_feature_undo_title: "Unlimited undo",
  landing_feature_undo_body: "20-step history with keyboard shortcuts. Experiment without fear.",
  // Use cases
  landing_useCasesEyebrow: "Use cases",
  landing_useCasesTitle: "Built for real job seekers",
  landing_useCasesSubtitle: "Whether you're starting out, switching careers, or applying abroad — the right templates are there.",
  landing_useCase_german_title: "German job market",
  landing_useCase_german_body: "Classic Lebenslauf with photo, date of birth, nationality, and tabular structure — exactly the way German HR expects.",
  landing_useCase_international_title: "International applications",
  landing_useCase_international_body: "English section titles, US-style dates, photo optional. One click, two languages.",
  landing_useCase_changer_title: "Career changers",
  landing_useCase_changer_body: "Highlight skills over chronology: reorderable sections, featured projects, flexible layout.",
  landing_useCase_variants_title: "Multiple variants",
  landing_useCase_variants_body: "Save a tailored version per role without overwriting your main CV.",
  // Templates
  landing_templatesEyebrow: "Templates",
  landing_templatesTitle: "10 professional templates",
  landing_templatesSubtitle: "Pick one — your content stays. Switch any time.",
  landing_templates_ats: "ATS-safe",
  landing_templates_twoCol: "Two-column",
  // Free section
  landing_freeEyebrow: "Pricing",
  landing_freeTitle: "Truly free.",
  landing_freeBody: "No hidden fees, no trial, no paywall at export. If it saves you time, a GitHub star or a coffee is appreciated.",
  landing_freeBullet1: "No ads",
  landing_freeBullet2: "No paywalled exports",
  landing_freeBullet3: "No account required",
  landing_freeBullet4: "Open source on GitHub",
  // JSON section
  landing_jsonEyebrow: "Data ownership",
  landing_jsonTitle: "Own your data",
  landing_jsonSubtitle: "Import and export your CV as portable JSON. Version-control it with Git, diff it, carry it with you.",
  landing_jsonCopy: "Copy",
  landing_jsonCopied: "Copied",
  landing_jsonWhyTitle: "Why JSON?",
  landing_jsonWhy1: "Portable — works with any editor",
  landing_jsonWhy2: "Versionable — Git-friendly",
  landing_jsonWhy3: "Future-proof — open standard",
  landing_jsonWhy4: "Automatable — drop into AI pipelines",
  // FAQ
  landing_faqEyebrow: "FAQ",
  landing_faqTitle: "Frequently asked",
  landing_faq_free_q: "Is it really free?",
  landing_faq_free_a: "Yes. Every feature — templates, PDF/DOCX export, versions, multi-language — is free and will stay that way. The project is open source and appreciates a GitHub star.",
  landing_faq_data_q: "Where is my data stored?",
  landing_faq_data_a: "Only locally in your browser (LocalStorage). No server, no cloud, no account. If you clear your browser, the data is gone — so export to JSON or PDF regularly.",
  landing_faq_german_q: "Does it follow German Lebenslauf standards?",
  landing_faq_german_a: "Yes. Templates follow DIN 5008, correct date formats (MM.YYYY), German section titles, date of birth and nationality. Several templates (e.g. \"Tabellarisch\") are explicitly modeled on the classic German CV.",
  landing_faq_ats_q: "Is the export ATS-compatible?",
  landing_faq_ats_a: "Eight of ten templates are ATS-friendly (single-column, clean structure). There is also a dedicated \"ATS-PDF\" export that produces a plain-text version — ideal for automated applicant tracking systems.",
  landing_faq_offline_q: "Does it work offline?",
  landing_faq_offline_a: "After the first load, yes. Editing, preview, and export run entirely in the browser. No internet connection required.",
  landing_faq_formats_q: "Which export formats are supported?",
  landing_faq_formats_a: "PDF (styled A4), ATS-PDF (plain text for applicant tracking systems), DOCX (editable in Word), and JSON (for backup and versioning).",
  landing_faq_devices_q: "Can I use it on mobile?",
  landing_faq_devices_a: "Yes. The editor adapts with Edit/Preview tabs. For longer editing sessions, we recommend tablet or desktop.",
  landing_faq_multiple_q: "Can I save multiple versions?",
  landing_faq_multiple_a: "Yes, up to 20 snapshots. Each snapshot stores content plus layout. You can name, load, and rename them — perfect for tailoring per role.",
  // Contact
  landing_contactEyebrow: "Contact",
  landing_contactTitle: "Feedback, bugs, ideas",
  landing_contactBody: "This project thrives on feedback. File a bug, suggest a feature, or drop a star if it helped you.",
  landing_contact_github: "Open a GitHub issue",
  landing_contact_star: "Star on GitHub",
  landing_contact_email: "Send a message",
  landing_contact_coffee: "Buy me a coffee",
  // Contact dialog
  landing_contactDialog_title: "Message the developer",
  landing_contactDialog_description: "Leave your email and a short message — on submit, your mail app opens with everything pre-filled.",
  landing_contactDialog_emailLabel: "Your email",
  landing_contactDialog_emailPlaceholder: "you@example.com",
  landing_contactDialog_messageLabel: "Message",
  landing_contactDialog_messagePlaceholder: "What would you like to share? Feedback, bug, idea…",
  landing_contactDialog_submit: "Open mail app",
  landing_contactDialog_submitDirect: "Send message",
  landing_contactDialog_cancel: "Cancel",
  landing_contactDialog_hint: "Your mail app will open with the message pre-filled — nothing is sent without your confirmation.",
  landing_contactDialog_hintDirect: "Your message is delivered directly to the developer. Your email is only used to reply.",
  landing_contactDialog_errorEmail: "Please enter a valid email address.",
  landing_contactDialog_errorMessage: "Please write at least a few words.",
  landing_contactDialog_submitting: "Sending…",
  landing_contactDialog_successTitle: "Message sent",
  landing_contactDialog_successBody: "Thanks! I'll get back to you as soon as I can.",
  landing_contactDialog_successClose: "Close",
  landing_contactDialog_errorSubmit: "Sending failed. Please try again or send an email directly.",
  // Final CTA
  landing_finalCtaTitle: "Ready to start?",
  landing_finalCtaBody: "Your next CV is just a few clicks away.",
  landing_finalCtaButton: "Open the editor — free",
  // Footer
  landing_footerTagline: "A privacy-first CV builder for the German job market",
  landing_footerMadeWith: "Built with React, TypeScript & Tailwind",
  landing_footerRights: "Open source · Non-commercial license",
}
